config/routes.rb
Rails.application.routes.draw do

  get  '/signup',  to: 'utilisateurs#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  patch '/annonces/accepter/:id', to: 'annonces#accepter', as: 'annonces_accepter'
  patch '/annonces/annuler/:id', to: 'annonces#annuler', as: 'annonces_annuler'
  get '/mes/annonces', to: 'annonces#miennes', as: 'mes_annonces'
  get '/annonces/acceptées', to: 'annonces#travaux', as: 'mes_acceptes'
  get '/annonces/search', to: 'annonces#search', as: 'annonces_search'
  get '/home', to: 'sessions#home', as: 'home'

  resources :annonces
  resources :utilisateurs
  resources :secteur
  root 'sessions#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/annonce.rb
class Annonce < ApplicationRecord
  validates :titre, :descr, :createur, :secteur, presence: { message: "est absent" }
  dragonfly_accessor :logo
end

app/controllers/annonces_controller.rb
class AnnoncesController < ApplicationController
  def index
    @annonce = Annonce.all
    @secteur = Secteur.all
  end

  def show
    @annonce = Annonce.find(params[:id])
    @createur = Utilisateur.find(@annonce.createur)
    if(@annonce.preneur)
      @preneur = Utilisateur.find(@annonce.preneur)
    end
    if(@annonce.secteur)
      @secteur = Secteur.find(@annonce.secteur)
    end
  end

  def search
    @annonce = Annonce.where( secteur: params[:secteur] )
    @secteur = Secteur.all
    render 'index'
  end

  def edit
    @annonce = Annonce.find(params[:id])
    if (connecte? && (admin_connecte? || (sessions[:utilisateur_id] == @annonce.createur)))
      @secteur = Secteur.all
    else
      redirect_to root_path
    end
  end

  def update
    @annonce = Annonce.find(params[:id])
    if (@annonce.update_attributes(params.require(:annonce).permit(:titre, :descr, :secteur, :logo)))
      @annonce.save
      redirect_to @annonce
    else
      @secteur = Secteur.all
      render 'edit'
    end
  end

  def new
    if(connecte?)
      @annonce = Annonce.new
      @secteur = Secteur.all
    else
      redirect_to root_path
    end
  end

  def create
    if(connecte?)
      @annonce = Annonce.new(params.require(:annonce).permit(:titre, :secteur, :descr, :logo))
      @annonce.createur = utilisateur_courant.id

      if !@annonce.save
        @secteur = Secteur.all
        render 'new'
      else
        redirect_to @annonce
      end
    else
      redirect_to @annonce
    end
  end

  def destroy
    if(connecte? && (admin_connecte? || (sessions[:utilisateur_id] == @annonce.createur)))
      Annonce.find(params[:id]).destroy
    end
    redirect_to Annonce
  end

  def accepter
    @annonce = Annonce.find(params[:id])
    if(connecte? && pro_connecte?)
      @annonce.update preneur: session[:utilisateur_id]
    end
    redirect_to @annonce
  end

  def annuler
    @annonce = Annonce.find(params[:id])
    if(connecte? && ((session[:utilisateur_id] == @annonce.createur) || (session[:utilisateur_id] == @annonce.preneur) || admin_connecte?))
      @annonce.update preneur: nil
    end
    redirect_to @annonce
  end

  def miennes
    if !connecte?
      redirect_to Annonce
    end
    @annonce = Annonce.all
  end

  def travaux
    if !connecte? || !pro_connecte?
      redirect_to Annonce
    end
    @annonce = Annonce.all
  end
end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/views/annonces/edit.html.haml
.center
  %h1 Edition d'annonce

.row
  .col-md-6.col-md-offset-3
    = form_for @annonce, url: {action: "update"} do |f|

      %p Titre :
      = f.text_field :titre

      %p Descr :
      = f.text_area :descr, size: "60x12"

      %p A quel secteur d'activité correspond votre annonce?
      = f.select(:secteur) do
        - @secteur.each do |s|
          = content_tag(:option, s.nom, value: s.id)

      %p Photo :
      = f.file_field :logo

      = f.submit "Sauvegarder les changements", class: "btn btn-primary"

app/views/annonces/index.html.haml
.center
  %h1 Liste des annonces

=form_tag annonces_search_path, method: "get" do

  = label_tag(:secteur, "Secteur?")

  = select_tag(:secteur, options_from_collection_for_select(@secteur, :id, :nom))
  %p
  = submit_tag "Rechercher", class: "btn btn-primary"

%ul
  - @annonce.each do |annonce|
    .col-md-6.col-md-offset-3
      %li
        %h3 #{link_to annonce.titre, annonce_path(annonce.id)}
        -if (annonce.logo)
          = image_tag annonce.logo.thumb("400x200").url
        %h3.plus_bas

- if(connecte?)
  %p.align-right #{link_to "Créer une annonce", new_annonce_path}

app/views/annonces/miennes.html.haml
.center
  %h1 Vos annonces

%ul
  - @annonce.each do |annonce|
    - if annonce.createur == session[:utilisateur_id]
      %li
        %h3 #{link_to annonce.titre, annonce_path(annonce.id)}

%p.align-right #{link_to "Créer une annonce", new_annonce_path}

app/views/annonces/new.html.haml
.center
  %h1 Création d'annonce

- if(connecte?)
  .row
    .col-md-6.col-md-offset-3
      = form_for :annonce, url: annonces_path do |f|
        = render 'shared/error_messagesAnnonces'

        %p Titre :
        = f.text_field :titre, class: 'form-control'

        %p Description :
        = f.text_area :descr, size: "60x12", class: 'form-control'

        %p A quel secteur d'activité correspond votre annonce?
        = f.select(:secteur) do
          - @secteur.each do |s|
            = content_tag(:option, s.nom, value: s.id)

        %p Photo :
        = f.file_field :logo

        = f.submit "Créer", class: "btn btn-primary"

- else
  %p Vous devez #{link_to "vous connecter", login_path} pour créer une annonce.

app/views/annonces/show.html.haml
.center
  %h1= @annonce.titre
%p= @annonce.descr

- if(@secteur)
  %p.align-right
    Secteur de l'annonce :
    = @secteur.nom

- if(@annonce.logo)
  = image_tag @annonce.logo.thumb("600x300").url

%p.align-right
  Annonce proposée par :
  =link_to utilisateur_path(@createur.id) do
    = @createur.prenom
    = @createur.nom

- if(@preneur)
  %p.align-right
    Annonce acceptée par :
    =link_to utilisateur_path(@preneur.id) do
      = @preneur.prenom
      = @preneur.nom
- if(connecte? && (admin_connecte? || (utilisateur_courant.id == @annonce.createur)))
  %p #{link_to "Editer", edit_annonce_path(@annonce.id)}
  %p #{link_to "Supprimer", @annonce, method: :delete, data: { confirm: "Vous êtes sûr?" }}

  -if @preneur
    =form_tag annonces_annuler_path(@annonce), method: "patch" do
      = submit_tag "Refuser le professionnel", class: "btn btn-primary", data: { confirm: "Etes-vous sûr?" }

- elsif(connecte? && pro_connecte? && (@annonce.preneur == nil))
  =form_tag annonces_accepter_path, method: "patch", data: { confirm: "Etes-vous sûr?"} do
    = submit_tag "Accepter l'annonce", class: "btn btn-primary"

- elsif(connecte? && pro_connecte? && (@annonce.preneur == session[:utilisateur_id]))
  =form_tag annonces_annuler_path(@annonce), method: "patch" do
    = submit_tag "Annuler l'acceptation", class: "btn btn-primary", data: { confirm: "Etes-vous sûr?" }

app/views/annonces/travaux.html.haml
.center
  %h1 Les annonces que vous avez acceptées

%ul
  - @annonce.each do |annonce|
    - if annonce.preneur == session[:utilisateur_id]
      %li
        %h3 #{link_to annonce.titre, annonce_path(annonce.id)}

%p.align-right #{link_to "Créer une annonce", new_annonce_path}