config/routes.rb
Rails.application.routes.draw do

  get  '/signup',  to: 'utilisateurs#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  patch '/annonces/accepter/:id', to: 'annonces#accepter', as: 'annonces_accepter'
  patch '/annonces/annuler/:id', to: 'annonces#annuler', as: 'annonces_annuler'
  get '/mes/annonces', to: 'annonces#miennes', as: 'mes_annonces'
  get '/annonces/acceptées', to: 'annonces#travaux', as: 'mes_acceptes'
  get '/annonces/search', to: 'annonces#search', as: 'annonces_search'
  get '/home', to: 'sessions#home', as: 'home'

  resources :annonces
  resources :utilisateurs
  resources :secteur
  root 'sessions#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.haml
%header{:class => "navbar navbar-fixed-top navbar-inverse"}
  .container
    #{link_to "Bricoschool", root_path, id: "logo"}
    %nav
      %ul{:class => "nav navbar-nav navbar-right"}
        %li #{link_to "Annonces", annonces_path}
        %li #{link_to "Professionnels", utilisateurs_path}
        - if connecte?
          %li{:class => "dropdown"}
            %a{:href => "#", :class => "dropdown-toggle", :data => {:toggle => "dropdown"}}
              Compte
              %b.caret
            %ul{:class => "dropdown-menu"}
              %li #{link_to "Profil", utilisateur_courant}
              %li #{link_to "Vos annonces", mes_annonces_path}
              - if pro_connecte?
                %li #{link_to "Vos annonces acceptées", mes_acceptes_path}
              %li{:class => "divider"}
              %li #{link_to "Se déconnecter", logout_path, method: :delete}
        - else
          %li #{link_to "Se connecter", login_path}
          %li #{link_to "S'inscrire", signup_path}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bricoschool</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div><%= flash[:info] %></div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>